#ifndef LIGHTCULLINGDEBUG_HEADER
#define LIGHTCULLINGDEBUG_HEADER

struct Debug
{
    // scrbounds debug
    float3 vMin;
    float3 vMax;
    float3 hullVertex0;
    float3 hullVertex1;
    float3 hullVertex2;
    float3 hullVertex3;
    float3 center;
    float radius;
    uint allVisibleOrInvisible;
    float3 allVMin;
    float3 allVMax;
    float3 BSVMin;
    float3 BSVMax;
    float3 BSVMin2;
    float3 BSVMax2;
    float3 FinalVMin;
    float3 FinalVMax;
    float3 clippedConvexVMin;
    float3 clippedConvexVMax;
};

int _LightLoopCullingDebugMode;

#define LIGHTCULLINGDEBUG_SCRBOUND_HULLAABB 1
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLVERTICES 2
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLCENTER 4
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLCLIPPED 8
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLVERTICEVISIBILITY 16
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLSPHERICALREDUCTION 32
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLSPHEREVOLUMEFORREDUCTION 64
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLFINAL 128
#define LIGHTCULLINGDEBUG_SCRBOUND_HULLCLIPPEDCONVEX 256

#define LIGHTCULLINGDEBUG_LIGHTLIST_DEPTH 512
#define LIGHTCULLINGDEBUG_LIGHTLIST_DISTANCETOLIGHT 1024
#define LIGHTCULLINGDEBUG_LIGHTLIST_VIEWPOS 2048
#define LIGHTCULLINGDEBUG_LIGHTLIST_NBLIGHTPERTILE 4096
#define LIGHTCULLINGDEBUG_LIGHTLIST (LIGHTCULLINGDEBUG_LIGHTLIST_DEPTH | LIGHTCULLINGDEBUG_LIGHTLIST_DISTANCETOLIGHT | LIGHTCULLINGDEBUG_LIGHTLIST_VIEWPOS | LIGHTCULLINGDEBUG_LIGHTLIST_NBLIGHTPERTILE)
#endif